### ISSUE TITLE
Can't force config mode

### ISSUE THREAD

**Issue by oldmanskier** [drmpf/ESPAutoWiFiConfig#1]
Can't force reconfiguration on ESP-01s.  EEPROM not erased.

**Comment by drmpf** [comment]
To force into config mode, turn off the router it is currently connected to.
Can also force confing mode by power cycle within 10 sec of startup when slow flashing or led off (connected)

Tested with the [ESP8266ConfigExample.ino](https://github.com/drmpf/ESPAutoWiFiConfig/blob/main/examples/ESP8266ConfigExample/ESP8266ConfigExample.ino) with ledPin set to 2 for ESP_01S (only one led)
NOTE: no default config specified in ESPAutoWiFiConfig.cpp in defaultNetworkSettings().
With router off ESP_01S switched to AssessPoint mode after timeout (slow flash -> fast flash)
Entered different router config (mobile hotspot), rebooted, ESP_01S connected.
Turned off mobile hotspot and ESP_01S again switched to AccessPoint after timeout.
Entered main router config and rebooted, ESP_01S connected to main router.

Test power cycling to switch between using stored config and forcing into AccessPoint mode.

So could not reproduce this problem.
